"""decouple mock tasks from the domain schema

mock_tasks stands in for Linear or Jira. A real tracker holds our identifier
as an opaque reference in a custom field, so a foreign key here would couple
the "external" system to our schema and quietly make the integration easier
than the real one.

Revision ID: c36697a96994
Revises: 4363f24e9155
Create Date: 2026-09-01 23:21:01.560375

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c36697a96994"
down_revision: str | Sequence[str] | None = "4363f24e9155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_mock_tasks_source_commitment_id"),
        "mock_tasks",
        ["source_commitment_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_mock_tasks_source_commitment_id_commitments"), "mock_tasks", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_mock_tasks_source_commitment_id_commitments"),
        "mock_tasks",
        "commitments",
        ["source_commitment_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_mock_tasks_source_commitment_id"), table_name="mock_tasks")
    # ### end Alembic commands ###
